webtalk_init -webtalk_dir Z:/ECE/ECE524L/Lab3_new/stream_interleaver_pt2/stream_interleaver_pt2.sim/sim_1/behav/xsim/xsim.dir/p2_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct  3 17:38:21 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211292476_1777527091_210688089_666" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ed1af7ab-6ce2-4d1e-b951-35d6e2d2392c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5f008112e07244928af415a1145c41ab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) E-2104G CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "13" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7308_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1444708156 -regid "211292476_1777527091_210688089_666" -xml Z:/ECE/ECE524L/Lab3_new/stream_interleaver_pt2/stream_interleaver_pt2.sim/sim_1/behav/xsim/xsim.dir/p2_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html Z:/ECE/ECE524L/Lab3_new/stream_interleaver_pt2/stream_interleaver_pt2.sim/sim_1/behav/xsim/xsim.dir/p2_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm Z:/ECE/ECE524L/Lab3_new/stream_interleaver_pt2/stream_interleaver_pt2.sim/sim_1/behav/xsim/xsim.dir/p2_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
